### PR TITLE
Add Tinyb

### PR DESCRIPTION
**Pull request by twgraham**
This PR adds TinyB (https://github.com/intel-iot-devkit/tinyb) to the server as a dependency. It will allow the server to interact further with IoT sensors for monitoring e.g. TI Sensor Tag

### CODE REVIEW

**Comment by twgraham** [comment]
I just realised we're missing the native api libraries here. I'll see if I can add them to the project too before we merge this.

**Comment by twgraham** [comment]
So I added the native libraries, and did some manual testing to make sure tinyb could run. It seems like the library is loading fine now, but I was having trouble getting full results (scanning for bluetooth devices) because Docker for Mac [can't expose tty devices (usb/bluetooth etc) to containers](https://github.com/docker/for-mac/issues/900). This is due to a lack of functionality in underlying xyhve (hypervisor) layer.

As a workaround we can run in linux VM's. I'm not sure whether Docker for Windows will have the same issues. I think the old docker toolbox would be fine because it uses linux VM's.

**Comment by kutluo** [comment]
I will check this today on docker for windows to see if it has the same problem.

**Comment by twgraham** [comment]
Can verify that it works on Linux VM. I wrote a quick trial:

```Java
BluetoothManager manager = BluetoothManager.getBluetoothManager();
boolean started = manager.startDiscovery();

log.info("Bluetooth started: " + started);

manager.find(BluetoothType.NONE, null, null, null);

log.info("Devices discovered:");

for (BluetoothDevice device : manager.getDevices()) {
    log.info(device.getName() + " - " + device.getAddress());
}

manager.stopDiscovery();
```

And when I ran it, I got this result 😃

image

I'm not concerned about the exception thrown when attempting to stop discovery - I didn't protect against this.

**Comment by kutluo** [comment]
I couldn't get this working either, I was stuck at an earlier step couldn't even get the bluetooth manager, however passing the review because it works in linux. 
`Exception in thread "main" java.lang.RuntimeException: Error getting object manager client: Error calling StartServiceBy
Name for org.bluez: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return c
ode 1`

**Comment by twgraham** [comment]
Yeah this is similar to the error i saw on docker for mac. Atleast its consistent

**Pull request merged**
